DROP TRIGGER PROG_TRIGGER;
DROP SEQUENCE PROG_SEQUENCE;
DROP TRIGGER LOC_TRIGGER;
DROP SEQUENCE LOC_SEQUENCE;
DROP TABLE EVENT_PARTICIPANTS;
DROP TABLE EVENT;
DROP TABLE PHOTO_COMMENTS;
DROP TABLE PHOTO_TAG;
ALTER TABLE PHOTO DROP CONSTRAINT PHOTO_REF_ALBUM;
DROP TABLE ALBUM;
DROP TABLE PHOTO;
DROP TABLE USER_MESSAGE;
DROP TABLE USER_FRIENDS;
DROP TABLE USER_COLLEGE;
DROP TABLE COLLEGE;
DROP TABLE PROFILE;
DROP TABLE LOCATION;


